email:
  from:       plyovchev.sumup.temp@gmail.com
  password:   'btvl ljca menr udgj'
  recipients: 
    - plt3ch@gmail.com
  smtp_host:   smtp.gmail.com
  smtp_port:   587

slack:
  webhook_url: https://hooks.slack.com/services/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

database: 
  dialect: postgres
  host: postgres
  port: 5432
  username: postgres
  dbname: postgres
  password: postgres